name: ESP32 CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:latest
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build project
      run: |
        source /opt/esp/idf/export.sh
        idf.py build
